---
# Install
- name: Create target dir
  file:
    path: /usr/local/sbin
    group: root
    owner: root
    state: directory
    mode: 0755
  become: true

- name: Download script
  get_url:
      url: https://raw.githubusercontent.com/zfsonlinux/zfs-auto-snapshot/master/src/zfs-auto-snapshot.sh
      force: "{{ autosnap_update }}"
      mode: 0755
      dest: "{{ autosnap_bin }}"
      group: root
      owner: root
  become: true

- name: Download man page
  get_url:
      url: https://raw.githubusercontent.com/zfsonlinux/zfs-auto-snapshot/master/src/zfs-auto-snapshot.8
      force: "{{ autosnap_update }}"
      mode: 0644
      dest: /usr/share/man/man8/zfs-auto-snapshot.8
      group: root
      owner: root
  become: true

- name: add PATH to cron
  cron:
    env: yes
    name: PATH
    value: "/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin"
    user: root
    state: present
  become: yes

- name: Set up hourly/daily/weekly/monthly cron job
  cron:
    name: "zfs auto snapshot {{ item.label }}"
    special_time: "{{ item.label }}"
    job: "{{ autosnap_bin }} {{ autosnap_args }} --label={{ item.label }} --keep={{ item.keep }} //"
    user: root
  become: true
  with_items:
    - { label: hourly,  keep: "{{ zfs_keep_hourly }}" }
    - { label: daily,   keep: "{{ zfs_keep_daily }}" }
    - { label: weekly,  keep: "{{ zfs_keep_weekly }}" }
    - { label: monthly, keep: "{{ zfs_keep_monthly }}" }

- name: Set up frequent cron job
  cron:
    name: "zfs auto snapshot frequent"
    minute: "*/{{ zfs_keep_frequent_interval }}"
    job: "{{ autosnap_bin }} {{ autosnap_args }} --label=frequent --keep={{ zfs_keep_frequent }} //"
    user: root
  become: true

- name: Update ZFS properties
  zfs:
    name: "{{ item.key }}"
    "com.sum:auto-snapshot": "{{ item.value.enabled | default(true) | lower }}"
    "com.sun:auto-snapshot:frequent": "{{ item.value.frequent | default(false) | lower }}"
    "com.sun:auto-snapshot:hourly": "{{ item.value.hourly | default(false) | lower }}"
    "com.sun:auto-snapshot:daily": "{{ item.value.daily | default(false) | lower }}"
    "com.sun:auto-snapshot:weekly": "{{ item.value.weekly | default(false) | lower }}"
    "com.sun:auto-snapshot:monthly": "{{ item.value.monthly | default(false) | lower }}"
    state: present
  become: true
  with_dict: "{{ zfs_datasets }}"
